services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file: .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - proxy-network

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file: .env
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network